### ISSUE TITLE
Run trojan on Mac with M1 CPU

### ISSUE THREAD

**Issue by yufengwa** [leiless/trojan-darwin-universal#1]
I am trying to run trojan (version 1.16.0) on my new Mac with M1 chip, however, it reports "Bad CPU type in executable: ./trojan", I opened an issue in trojan-gfw/trojan, and he guide me to your repo, would you please tell the exact workflow to config on Mac with M1 CPU. Thanks!

**Comment by leiless** [comment]
> I am trying to run trojan (version 1.16.0) on my new Mac with M1 chip, however, it reports "Bad CPU type in executable: ./trojan"

Which trojan arch do you use? `x86_64`?

If you using `x86_64` arch previously, please try with https://github.com/leiless/trojan-darwin-universal/releases/tag/v1.16.0

However, I remember that macOS can run `x86_64` arch software with Rosetta 2. which it reports bad CPU type is weird to me..

Also, which macOS version do you use?

**Comment by yufengwa** [comment]
> > I am trying to run trojan (version 1.16.0) on my new Mac with M1 chip, however, it reports "Bad CPU type in executable: ./trojan"
> 
> Which trojan arch do you use? `x86_64`?
> 
> If you using `x86_64` arch previously, please try with https://github.com/leiless/trojan-darwin-universal/releases/tag/v1.16.0
> 
> However, I remember that macOS can run `x86_64` arch software with Rosetta 2. which it reports bad CPU type is weird to me..
> 
> Also, which macOS version do you use?

Thanks, I have figured it out, I succeed by installing Trojan-QT5.dmg with Rosetta, it works now, I use macOS Big Sur version 11.0.

**Comment by leiless** [comment]
Glad to hear :-)

**Comment by leiless** [comment]
https://github.com/trojan-gfw/trojan/issues/589
